//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoWeather
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeatherEntry
    {
        public int EntryID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public double Temp { get; set; }
        public double Humidity { get; set; }
        public double Td { get; set; }
        public short Pressure { get; set; }
        public string WindDir { get; set; }
        public Nullable<short> WindSpd { get; set; }
        public Nullable<short> Cloudness { get; set; }
        public Nullable<short> h { get; set; }
        public Nullable<short> VV { get; set; }
        public string WeatherPhen { get; set; }
    }
}
